"use strict";

window.PORTFOLIO = {
  featured: {
    web: [
      {
        title: "Byte Vermin",
        subtitle: "Original cybersecurity toy universe",
        image: "images/webp2.webp",
        href: "https://github.com/domcalvello/BYTE-VERMIN",
        type: "Website",
      },
      {
        title: "Buffalo Remixed",
        subtitle: "Buffalo Bills NFL inspired fan-apparel storefront",
        image: "images/webp1.webp",
        href: "https://github.com/domcalvello/BUFFALOREMIXED",
        type: "Website",
      },
      {
        title: "System Strike",
        subtitle: "Cybersecurity themed fighting-game",
        image: "images/webp3.webp",
        href: "https://github.com/domcalvello/SYSTEM-STRIKE",
        type: "Website",
      },
      {
        title: "M & J Stereo Receiver",
        subtitle: "Interactive browser-based music player",
        image: "images/webp4.webp",
        href: "https://github.com/domcalvello/RECORDPLAYER",
        type: "Website",
      },
      {
        title: "JACKPOT Music",
        subtitle: "Las Vegas based DJ & producer web hub",
        image: "images/webp5.webp",
        href: "https://github.com/domcalvello/JACKPOT-MUSIC",
        type: "Website",
      },
    ],
    graphic: [
      { title: "The Elephant House", subtitle: "Lost Photos series", image: "images/lostphotos1.webp", technique: "AI-assisted photography / Experimental prompting" },
      { title: "The Neighbors", subtitle: "Lost Toys packaging series", image: "images/losttoys1.webp", technique: "AI-assisted + package design" },
      { title: "Presidents at War", subtitle: "Fighting game visual concept", image: "images/game17.webp", technique: "AI-assisted + compositing" },
      { title: "END DAYS album art", subtitle: "Album artwork", image: "images/album4.webp", technique: "AI-assisted + Photoshop" },
      { title: "Buffalo Bricks Mascot", subtitle: "Character/logo design", image: "images/cartoon6.webp", technique: "AI-assisted illustration" },
      { title: "Gucci x Ghirardelli sneaker", subtitle: "Brand mash-up series", image: "images/diffdesigns10.webp", technique: "AI-assisted + art direction" },
      { title: "Legacy Device Group Therapy", subtitle: "3D visual concept", image: "images/dimensionals17.webp", technique: "AI-assisted + compositing" },
      { title: "GAG GEM MINT 10 AOL Trial CD Error slab", subtitle: "Graded object concept", image: "images/gag3.webp", technique: "AI-assisted concept" },
      { title: "DJ themed fighting game: Steve Aoki vs. Tiesto", subtitle: "Video game concept", image: "images/game14.webp", technique: "AI-assisted + interface design" },
      { title: "Red, White & Bruised logo", subtitle: "Logo design", image: "images/logo4.webp", technique: "AI-assisted + Photoshop" },
      { title: "Rembrandt paints the X-Men: Rogue", subtitle: "Marvel × Rembrandt series", image: "images/marvelxrem1.webp", technique: "AI-assisted fine-art + Codex" },
      { title: "Server room fiber optic whip", subtitle: "Open world video game series", image: "images/openworld6.webp", technique: "AI-assisted environment design" },
      { title: "System Strike: Phishing", subtitle: "Character design", image: "images/sysstrike4.webp", technique: "AI-assisted + art direction" },
      { title: "Bird Machine album art", subtitle: "Album artwork", image: "images/graphics/BirdMachineBoot.webp", technique: "Photoshop" },
      { title: "Igloo presents: The Family Picnic", subtitle: "Event flyer", image: "images/graphics/IGLOOFAMPICNIC.webp", technique: "Photoshop" },
    ],
    video: [
      {
        title: "Video Editing + YouTube",
        subtitle: "Canva + AI + Ableton Live",
        service: "Song: Next Hellifornia YouTube edit",
        ratio: "landscape",
        embed: "https://www.youtube-nocookie.com/embed/jKPLJN-z9qg",
        href: "https://www.youtube.com/watch?v=jKPLJN-z9qg",
        thumb: "https://i.ytimg.com/vi/jKPLJN-z9qg/maxresdefault.jpg",
      },
      {
        title: "Video Editing + YouTube",
        subtitle: "Canva + AI + Ableton Live",
        service: "Song: Money In The Bank YouTube edit",
        ratio: "landscape",
        embed: "https://www.youtube-nocookie.com/embed/oUZAfSvIqy8",
        href: "https://www.youtube.com/watch?v=oUZAfSvIqy8",
        thumb: "https://i.ytimg.com/vi/oUZAfSvIqy8/maxresdefault.jpg",
      },
      {
        title: "Video Editing + Instagram",
        subtitle: "Photoshop + Ableton Live",
        service: "Song: Killa social media edit",
        ratio: "portrait",
        embed: "https://www.instagram.com/reel/BEhxyaLvNp5/embed/",
        href: "https://www.instagram.com/reel/BEhxyaLvNp5/",
      },
      {
        title: "Video Editing + Instagram",
        subtitle: "Photoshop + AI + Ableton Live",
        service: "Song: Cash Out social media edit",
        ratio: "portrait",
        embed: "https://www.instagram.com/reel/DQseI0JASlI/embed/",
        href: "https://www.instagram.com/reel/DQseI0JASlI/",
      },
    ],
    audio: [

      { title: "SwaggleRock", subtitle: "SoundCloud catalog", soundcloud: "https://soundcloud.com/swagglerock", accent: "#ff3434" },
      { title: "SwaggleRock Edits", subtitle: "SoundCloud catalog", soundcloud: "https://soundcloud.com/swagglerock-edits", accent: "#00f7ff" },
      { title: "JACKPOT", subtitle: "SoundCloud catalog", soundcloud: "https://soundcloud.com/jackpotlasvegas", accent: "#d4ae45" },      
      { title: "Shooter McNappin", subtitle: "SoundCloud catalog", soundcloud: "https://soundcloud.com/shootermcnappin", accent: "#ff2ea6" },
    ],
  },

  archive: {
    traditional: [
      "TELLME.webp", "heistflyer.webp", "10bandsbootleg.webp", "equinoxigloobanner.webp",
      "TRANSITIONEDITS.webp", "BlewMyMind.webp", "GYBDSRrmx.webp", "deepoceansmix.webp",
      "WILDbootleg.webp", "KNKdoubleDrop.webp", "LOCDSHOOTERCOVER.webp", "pizzaparty.webp",
      "bannerigloofeb21.webp", "SRtvglitch.webp", "trapnationbanner.webp", "redlipslocdout.webp",
      "RufusG.webp", "BirdMachineBoot.webp", "icantstop.webp", "shootermcnappin.webp",
      "shootercover.webp", "COLDFLEXMIX.webp", "CLOSEcover.webp", "IGLOOFAMPICNIC.webp",
      "shootermerch.webp", "srbanner.webp", "igloofeb21.webp", "THURSBAMBINO.webp",
      "feelthevolume.webp", "fbbannersr.jpg", "tourlist.jpg",
    ],
    aiFamilies: [
      { key: "album", title: "Album Artwork", count: 6 },
      { key: "cartoon", title: "Cartoon Design", count: 7 },
      { key: "diffdesigns", title: "Design Concepts", count: 10 },
      { key: "dimensionals", title: "Dimensional Artwork", count: 20 },
      { key: "gag", title: "G.A.G. Designs", count: 4 },
      { key: "game", title: "Game Concepts", count: 21 },
      { key: "logo", title: "Logo Design", count: 7 },
      { key: "lostphotos", title: "Lost Photos Series", count: 11 },
      { key: "losttoys", title: "Lost Toys Series", count: 3 },
      { key: "marvelxrem", title: "Marvel × Rembrandt Series", count: 12 },
      { key: "openworld", title: "Open World Game Concepts", count: 9 },
      { key: "sysstrike", title: "System Strike Game Design", start: 0, count: 7 },
    ],
  },
};
